# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/koushikmgithub/concourse-spring-boot-maven.git
    branch: master

- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml
  - put: cf
    params:
      manifest: source-code/manifest.yml
      path: build-output/concourse-spring-boot-maven-0.0.1-SNAPSHOT.jar