# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---
resources:
- name: src-code
  type: git
  source:
    uri: https://github.com/koushikmgithub/concourse-spring-boot-maven.git
    branch: master

- name: cf
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: build
  public: true
  plan:
  - get: src-code
    trigger: true
  - task: build
    privileged: true
    #file: src-code/ci/build.yml
    config:
      platform: linux
      inputs:
      - name: src-code
      outputs:
      - name: build-output
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: "8"
      run:
        path: sh
        args:
        - -exc
        - |
          export TERM=dumb
          cd src-code
          ./mvnw clean install
          cd ..
          cp src-code/target/concourse-spring-boot-maven-0.0.1-SNAPSHOT.jar  build-output/.
  - put: cf
    params:
      manifest: src-code/manifest.yml
      path: build-output/concourse-spring-boot-maven-0.0.1-SNAPSHOT.jar
